"""Create quiz specific question models

Revision ID: 8c31d6b4ddb8
Revises: 47584f0cdd70
Create Date: 2025-06-08 17:35:03.181040

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8c31d6b4ddb8'
down_revision = '47584f0cdd70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quizzes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('level_id')
    )
    op.create_table('quiz_questions',
    sa.Column('id', sa.Integer(), nullable=False), # Added primary key for QuizQuestion
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('question_type', sa.Enum('TEXT', 'IMAGE', 'AUDIO', name='questiontype'), nullable=False), # Using explicit Enum type
    sa.Column('question_content', sa.String(length=255), nullable=False),
    sa.Column('answer_type', sa.Enum('MULTIPLE_CHOICE', 'FILL_IN_BLANK', name='answertype'), nullable=False), # Using explicit Enum type
    sa.Column('correct_answer', sa.String(length=255), nullable=True),
    sa.Column('order_in_quiz', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.PrimaryKeyConstraint('id'), # Primary key for QuizQuestion
    sa.UniqueConstraint('quiz_id', 'order_in_quiz', name='_quiz_question_order_uc')
    )
    op.create_table('quiz_choices',
    sa.Column('id', sa.Integer(), nullable=False), # Primary key for QuizChoice
    sa.Column('quiz_question_id', sa.Integer(), nullable=False),
    sa.Column('choice_type', sa.Enum('TEXT', 'IMAGE', 'AUDIO', name='choicetype'), nullable=False), # Using explicit Enum type
    sa.Column('content', sa.String(length=255), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_question_id'], ['quiz_questions.id'], ),
    sa.PrimaryKeyConstraint('id') # Primary key for QuizChoice
    )

    # REMOVED: The problematic sections.name unique constraint creation/deletion
    # This was causing issues due to existing duplicate data in your sections table.
    # If you need sections.name to be unique, you must first clean up the data
    # and then create a separate migration specifically for that constraint.

    # Modify existing question_choices table (if needed, this was from previous migration)
    with op.batch_alter_table('question_choices', schema=None) as batch_op:
        batch_op.alter_column('choice_type',
               existing_type=mysql.ENUM('TEXT', 'IMAGE', 'VOICE'), # Old type if it was from previous migration
               type_=sa.Enum('TEXT', 'IMAGE', 'AUDIO', name='choicetype'), # New type from app.enums.ChoiceType
               existing_nullable=False)


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # REVERT: Modifications to question_choices table
    with op.batch_alter_table('question_choices', schema=None) as batch_op:
        batch_op.alter_column('choice_type',
               existing_type=sa.Enum('TEXT', 'IMAGE', 'AUDIO', name='choicetype'), # Revert to old type
               type_=mysql.ENUM('TEXT', 'IMAGE', 'VOICE'), # Assuming this was the original type
               existing_nullable=False)

    # REMOVED: The problematic sections.name unique constraint drop

    op.drop_table('quiz_choices') # Drop quiz_choices first due to foreign key
    op.drop_table('quiz_questions') # Then drop quiz_questions
    op.drop_table('quizzes') # Then drop quizzes

    # ### end Alembic commands ###
